FishOASIS.fig = uifigure('Name','FishOASIS Processing Environment',...
    'Position',[600 500 320 230],...
    'CloseRequestFcn','clear(''all'',''global'');closereq');
set(FishOASIS.fig,'numb','off','menubar','none');

FishOASIS.bg = uibuttongroup(FishOASIS.fig,...
    'Title','Select Processing Routine',...
    'Position', [10 10 300 210],...
    'FontWeight','bold');


% Create buttons in the button group.
b1 = uibutton(FishOASIS.bg,...
    'text','Image Processing',...
    'Position',[10 150 170 30],...
    'UserData',1,...
    'ButtonPushedFcn',@(b1,event) runFishOASIS(b1,b1.UserData));

b2 = uibutton(FishOASIS.bg,...
    'Text','Concatenate Count Data',...
    'Position',[10 120 170 30],...
    'UserData',2,...
    'ButtonPushedFcn',@(b2,event) runFishOASIS(b2,b2.UserData));

b3 = uibutton(FishOASIS.bg,...
    'Text','Extract Acoustics',...
    'Position',[10 90 170 30],...
    'UserData',3,...
    'ButtonPushedFcn',@(b3,event) runFishOASIS(b3,b3.UserData));

b4 = uibutton(FishOASIS.bg,...
    'Text','View Images and Acoustics',...
    'Position',[10 60 170 30],...
    'UserData',4,...
    'ButtonPushedFcn',@(b4,event) runFishOASIS(b4,b4.UserData));

b5 = uibutton(FishOASIS.bg,...
    'Text','Plot Fish Count Data',...
    'Position',[10 30 170 30],...
    'UserData',5,...
    'ButtonPushedFcn',@(b5,event) runFishOASIS(b5,b5.UserData));


