%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Display Call Parameters
%
% Diplay the total count for each call type, as well as the parameters for
% the last logged call.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Call counts
MAIN.log.counttitle = uicontrol(MAIN.log.bg,'un','n','style','text',...
    'pos',[.3 .88 .2 .1],'str','Call Counts','foreg',[0 0 0],'backg',[.6 .6 1],...
    'fontsize',10,'fontweight','bold');

MAIN.log.call.h1count=uicontrol(MAIN.log.bg,'style','text','un','n',...
    'pos',[.3 .8 .2 .1],'str',num2str(PARAMS.log.count.h1),'foreg',[0 0 0],'backg',[.8 1 1]);

MAIN.log.call.h2count=uicontrol(MAIN.log.bg,'style','text','un','n',...
    'pos',[.3 .7 .2 .1],'str',num2str(PARAMS.log.count.h2),'foreg',[0 0 0],'backg',[1 .8 1]);


MAIN.log.call.h3count=uicontrol(MAIN.log.bg,'style','text','un','n',...
    'pos',[.3 .6 .2 .1],'str',num2str(PARAMS.log.count.h3),'foreg',[0 0 0],'backg',[1 1 .8]);


MAIN.log.call.h4count=uicontrol(MAIN.log.bg,'style','text','un','n',...
    'pos',[.3 .5 .2 .1],'str',num2str(PARAMS.log.count.h4),'foreg',[0 0 0],'backg',[.7 1 .7]);


MAIN.log.call.h5count=uicontrol(MAIN.log.bg,'style','text','un','n',...
    'pos',[.3 .4 .2 .1],'str',num2str(PARAMS.log.count.h5),'foreg',[0 0 0],'backg',[.8 .8 1]);

% Parameters of last logged call
MAIN.log.current.htitle = uicontrol(MAIN.log.bg,'style','text',...
    'un','n','pos',[.7 .81 .2 .1],'str','Last Logged Call',...
    'fontweight','bold','foreg',[0 0 0],'backg',[.6 .6 1]);

MAIN.log.current.hstarttitle = uicontrol(MAIN.log.bg,'style','text',...
    'un','n','pos',[.6 .7 .2 .1],'str','Start Time','fontweight','bold');
MAIN.log.current.hstart = uicontrol(MAIN.log.bg,'style','text',...
    'un','n','pos',[.6 .63 .2 .1],'str',PARAMS.log.current.start,...
    'foreg',[0 0 0],'backg',[.94 .94 .94]);

MAIN.log.current.hendtitle = uicontrol(MAIN.log.bg,'style','text',...
    'un','n','pos',[.8 .7 .2 .1],'str','End Time','fontweight','bold');
MAIN.log.current.hend = uicontrol(MAIN.log.bg,'style','text',...
    'un','n','pos',[.8 .63 .2 .1],'str',PARAMS.log.current.end,...
    'foreg',[0 0 0],'backg',[.94 .94 .94]);

MAIN.log.current.hlfreqtitle = uicontrol(MAIN.log.bg,'style','text',...
    'un','n','pos',[.6 .5 .2 .1],'str','Lower Frequency','fontweight','bold');
MAIN.log.current.hlfreq = uicontrol(MAIN.log.bg,'style','text',...
    'un','n','pos',[.6 .43 .2 .1],'str',PARAMS.log.current.lower,...
    'foreg',[0 0 0],'backg',[.94 .94 .94]);

MAIN.log.current.hufreqtitle = uicontrol(MAIN.log.bg,'style','text',...
    'un','n','pos',[.8 .5 .2 .1],'str','Upper Frequency','fontweight','bold');
MAIN.log.current.hufreq = uicontrol(MAIN.log.bg,'style','text',...
    'un','n','pos',[.8 .43 .2 .1],'str',PARAMS.log.current.upper,...
    'foreg',[0 0 0],'backg',[.94 .94 .94]);

% Save button
MAIN.log.hsave = uicontrol(MAIN.log.bg,'style','push',...
    'un','n','pos',[.5 .1 .4 .2],'str','Save Logged Calls',...
    'fontweight','bold','call','save_logged_calls');

% Load button
MAIN.log.hload = uicontrol(MAIN.log.bg,'style','push',...
    'un','n','pos',[.1 .1 .4 .2],'str','Load Logged Calls',...
    'fontweight','bold','call','load_logged_calls');








