h2.f = figure('toolbar','none','menu','none',...
    'name','Select Species',...
    'units','pixels','position',[100 100 1500 900],...
    'NumberTitle','off');

xpos = [20,320,620,920]; xgrid = meshgrid(xpos,1:35);
ypos = 880-[1:35]*25; ygrid = [ypos',ypos',ypos',ypos'];
for ii = 1:length(iDATA.day1.species.sfull)
    h2.b(ii) = uicontrol(h2.f,'style','checkbox',...
        'string',iDATA.day1.species.sfull(ii),...
        'units','pixels',...
        'position',[xgrid(ii) ygrid(ii) 250 35],...
        'fontsize',12);
end

h2.pb = uicontrol(h2.f,'style','pushbutton','string','OK',...
    'units','pixels','position',[700 20 100 50],...
    'callback','vals=get(h2.b,''Value'');checked=find([vals{:}]);close(h2.f)');

