h2.f = figure('toolbar','none','menu','none',...
    'name','Select Species',...
    'units','pixels','position',[600 100 900 800],...
    'NumberTitle','off');

xpos = [20,320,620]; xgrid = meshgrid(xpos,1:30);
ypos = 770-[1:30]*25; ygrid = [ypos',ypos',ypos'];
for ii = 1:length(iDATA.day1.species)
    h2.b(ii) = uicontrol(h2.f,'style','checkbox',...
        'string',iDATA.day1.species{ii},...
        'units','pixels',...
        'position',[xgrid(ii) ygrid(ii) 250 30],...
        'fontsize',12);
end

h2.pb = uicontrol(h2.f,'style','pushbutton','string','OK',...
    'units','pixels','position',[700 20 100 50],...
    'callback','vals=get(h2.b,''Value'');checked=find([vals{:}]);close(h2.f)');

